Add two sniffs to find and remove unused "use" clauses
wmde/WikibaseCodeSniffer pull request #11
Opened 2017-08-31 10:22 UTC by thiemowmde

2017-10-10 10:36 UTC, lucaswerkmeister approved these changes
I tried this out in the WikibaseQualityConstraints extension, where it removes 92 lines (all correct, as far as I can tell – I’ve just been sloppy with the imports). Seems to work fine.

2017-10-10 10:58 UTC, lucaswerkmeister requested changes
Found a bug:
```php
<?php
use A\B as /*_*/C;
$b = new C();
```
turns into
```php
<?php
C;
$b = new C();
```
which is invalid.

2017-10-10 13:14 UTC, addshore commented
Can this make its way into the mediawiki codesniffer?

2017-10-10 17:42 UTC, thiemowmde commented
@lucaswerkmeister: Good catch. That was easy to fix.

@addshore: See https://gerrit.wikimedia.org/r/375547. Both teams started to work on the same idea independently. Naturally, I like my version more. ;-)

2017-10-11 09:56 UTC, lucaswerkmeister commented
Sorry, there’s another broken case:
```php
<?php
use A\B as /** @var */ C;

$b = new C();
```
I tried expanding your fix, but it doesn’t work:
```patch
diff --git a/Wikibase/Sniffs/Namespaces/UnusedUseSniff.php b/Wikibase/Sniffs/Namespaces/UnusedUseSniff.php
index f2e94c4737..09dc891d09 100644
--- a/Wikibase/Sniffs/Namespaces/UnusedUseSniff.php
+++ b/Wikibase/Sniffs/Namespaces/UnusedUseSniff.php
@@ -24,6 +24,10 @@ public function process( PHP_CodeSniffer_File $phpcsFile, $stackPtr ) {
 		$useEndPtr = $phpcsFile->findNext( [
 			T_AS,
 			T_COMMENT,
+			T_DOC_COMMENT_OPEN_TAG,
+			T_DOC_COMMENT_CLOSE_TAG,
+			T_DOC_COMMENT_STRING,
+			T_DOC_COMMENT_TAG,
 			T_NS_SEPARATOR,
 			T_STRING,
 			T_WHITESPACE,
```
But this is a seriously pathological case… if the bug is too hard to fix, I think we could merge this without the bugfix.

2017-10-11 11:56 UTC, thiemowmde commented
Solved it. Thanks for poking this stuff!

2017-10-11 12:33 UTC, lucaswerkmeister commented
Great, thanks! That fix also looks more robust ;)

2017-10-11 12:34 UTC, lucaswerkmeister approved these changes

2017-10-11 12:34 UTC, merged